version: '3.8'

services:
  minecraft:
    image: itzg/minecraft-server:java17
    container_name: minecraft
    ports:
      - '25565:25565'
    environment:
      EULA: 'TRUE'
      VERSION: '1.18'
      MEMORY: '4G'
      MAX_MEMORY: '8G'
      SERVER_NAME: 'TaldykKTLtheBEST'
      ONLINE_MODS: true
      MODE: 'survival'
      DIFFICULTY: 'normal'
    volumes:
      - ./data:/data
    
